export const SERVER_REQUESTED = 'SERVER_REQUESTED';
export const SERVER_FULFILLED = 'SERVER_FULFILLED';
export const SERVER_REJECTED = 'SERVER_REJECTED';
export const UPDATE_GAME_STATE = 'UPDATE_GAME_STATE';
export const EAGER_UPDATE_GAME_STATE = 'EAGER_UPDATE_GAME_STATE';
export const SELECT_PIECE = 'SELECT_PIECE';
export const MOVE_PIECE = 'MOVE_PIECE';